/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Java_com_actor_testapplication_utils_Global */

#ifndef _Included_com_actor_testapplication_utils_Global
#define _Included_com_actor_testapplication_utils_Global
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_actor_testapplication_utils_Global
 * Method:    jniInit
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_actor_testapplication_utils_Global_jniInit
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     com_actor_testapplication_utils_Global
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_actor_testapplication_utils_Global_getString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
